(()=>{const KEY="mm_lead_popup_v1",SKIP=1000*60*60*24*7;if(localStorage.getItem(KEY)){return}const css=`
.mm-lead-overlay{position:fixed;inset:0;background:rgba(3,14,24,.68);backdrop-filter:blur(5px);z-index:200;display:none;align-items:center;justify-content:center;padding:20px}.mm-lead-overlay.open{display:flex}.mm-lead{position:relative;width:min(900px,100%);display:grid;grid-template-columns:.82fr 1.18fr;background:#fff;box-shadow:0 30px 80px rgba(0,0,0,.28);overflow:hidden}.mm-lead-side{padding:38px;background:#08243b;color:#fff;position:relative}.mm-lead-kicker{font:800 10px Inter;letter-spacing:.18em;color:#69b8ee}.mm-lead-side h2{font:700 38px/1 Space Grotesk;margin:16px 0;color:#fff}.mm-lead-side p{font:13px/1.7 Inter;color:#bfd0dc}.mm-lead-side ul{list-style:none;padding:0;margin:25px 0 0}.mm-lead-side li{font:11px/1.55 Inter;color:#dce7ee;padding:10px 0;border-bottom:1px solid rgba(255,255,255,.12)}.mm-lead-side li:before{content:"✓";color:#69b8ee;font-weight:900;margin-right:9px}.mm-lead-form{padding:34px}.mm-lead-close{position:absolute;right:14px;top:12px;width:34px;height:34px;border:0;background:transparent;font-size:24px;color:#718494;cursor:pointer}.mm-lead-form h3{font:700 25px Space Grotesk;color:#08243b;margin:0 0 8px}.mm-lead-form>p{font-size:11px;line-height:1.6;color:#6c7e8f;margin:0 0 22px}.mm-lead-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.mm-lead-field{display:grid;gap:6px}.mm-lead-field.full{grid-column:1/-1}.mm-lead-field label{font:800 8px Inter;letter-spacing:.12em;color:#718494}.mm-lead-field input,.mm-lead-field select{width:100%;border:1px solid #d9e3e9;padding:13px 12px;font:500 12px Inter;color:#173047;background:#fff}.mm-lead-consent{display:flex;gap:8px;align-items:flex-start;margin:13px 0;color:#6b7e8d;font-size:9px;line-height:1.5}.mm-lead-consent input{margin-top:2px}.mm-lead-submit{width:100%;border:0;background:#dd0f0f;color:#fff;padding:15px 18px;font:800 10px Inter;letter-spacing:.09em;cursor:pointer}.mm-lead-note{font-size:8px!important;color:#8293a0!important;margin-top:10px!important}.mm-lead-hp{position:absolute;left:-10000px;opacity:0}@media(max-width:720px){.mm-lead-overlay{padding:10px;align-items:flex-end}.mm-lead{grid-template-columns:1fr;max-height:92vh;overflow:auto;border-radius:8px}.mm-lead-side{display:none}.mm-lead-form{padding:24px}.mm-lead-grid{grid-template-columns:1fr}.mm-lead-field.full{grid-column:auto}}`;
const style=document.createElement("style");style.textContent=css;document.head.appendChild(style);
const overlay=document.createElement("div");overlay.className="mm-lead-overlay";overlay.innerHTML=`
<div class="mm-lead" role="dialog" aria-modal="true" aria-labelledby="mmLeadTitle">
<section class="mm-lead-side"><span class="mm-lead-kicker">ATENDIMENTO MULTIMARINE</span><h2>Descubra o próximo passo.</h2><p>Receba uma orientação inicial sobre cursos, qualificação e treinamentos para seu objetivo.</p><ul><li>Escolha pela sua área ou objetivo</li><li>Entenda quais formações podem fazer sentido</li><li>Fale diretamente com a equipe</li></ul></section>
<section class="mm-lead-form"><button class="mm-lead-close" type="button" aria-label="Fechar">×</button><h3 id="mmLeadTitle">Quero receber orientação</h3><p>Preencha seus dados e a equipe poderá retornar pelo canal de atendimento.</p>
<form id="mmLeadForm"><input class="mm-lead-hp" name="website" tabindex="-1" autocomplete="off">
<div class="mm-lead-grid"><div class="mm-lead-field"><label>NOME</label><input name="nome" required autocomplete="name"></div><div class="mm-lead-field"><label>TELEFONE / WHATSAPP</label><input name="telefone" required autocomplete="tel"></div><div class="mm-lead-field full"><label>E-MAIL</label><input name="email" type="email" required autocomplete="email"></div><div class="mm-lead-field full"><label>O QUE VOCÊ PROCURA?</label><select name="objetivo"><option>Quero trabalhar no offshore</option><option>Quero fazer um curso</option><option>Quero atualizar uma certificação</option><option>Quero qualificar minha equipe</option><option>Ainda não sei qual curso fazer</option></select></div></div>
<label class="mm-lead-consent"><input type="checkbox" name="consent" required> <span>Autorizo o contato para retorno sobre minha solicitação. Meus dados não serão usados para outro fim sem nova autorização.</span></label>
<button class="mm-lead-submit" type="submit">RECEBER ORIENTAÇÃO ↗</button><p class="mm-lead-note">O formulário prepara o atendimento no WhatsApp. A captação em CRM/e-mail pode ser conectada posteriormente a um endpoint seguro.</p></form></section></div>`;
document.body.appendChild(overlay);
const form=overlay.querySelector("#mmLeadForm"),close=()=>overlay.classList.remove("open");
overlay.querySelector(".mm-lead-close").addEventListener("click",close);overlay.addEventListener("click",e=>{if(e.target===overlay)close});document.addEventListener("keydown",e=>{if(e.key==="Escape")close});
const open=()=>{if(localStorage.getItem(KEY))return;overlay.classList.add("open");localStorage.setItem(KEY,String(Date.now()))};
setTimeout(open,11000);let armed=false;window.addEventListener("scroll",()=>{if(armed||localStorage.getItem(KEY))return;armed=true;if(scrollY>document.documentElement.scrollHeight*.38)open()},{passive:true});
form.addEventListener("submit",e=>{e.preventDefault();if(form.website.value)return;const d=new FormData(form),ctx=document.title,t=`Olá! Vim pelo site da MultiMarine. Nome: ${d.get("nome")}. Telefone/WhatsApp: ${d.get("telefone")}. E-mail: ${d.get("email")}. Objetivo: ${d.get("objetivo")}. Página: ${ctx}.`;window.open("https://wa.me/5522996172167?text="+encodeURIComponent(t),"_blank","noopener");close();localStorage.setItem(KEY,String(Date.now()+SKIP));});
})();