(()=>{const KEY='mm_trilha_v1',MAX=5;const read=()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x.slice(0,MAX):[]}catch{return[]}};const write=x=>{localStorage.setItem(KEY,JSON.stringify(x.slice(0,MAX)));render()};let items=read();
const style=document.createElement('style');style.textContent=`
.mm-trilha-fab{position:fixed;left:20px;bottom:20px;z-index:120;background:#08243b;color:#fff;border:1px solid #35546a;padding:11px 14px;border-radius:4px;display:flex;align-items:center;gap:9px;box-shadow:0 10px 24px rgba(8,36,59,.22);font:800 9px Inter;letter-spacing:.08em;text-transform:uppercase;cursor:pointer}
.mm-trilha-fab strong{display:inline-grid;place-items:center;min-width:20px;height:20px;border-radius:50%;background:#0568bf;color:#fff;font-size:9px}
.mm-trilha-panel{position:fixed;left:20px;bottom:62px;width:min(360px,calc(100vw - 30px));max-height:70vh;background:#fff;border:1px solid #d9e4eb;box-shadow:0 20px 50px rgba(8,36,59,.25);z-index:121;display:none;flex-direction:column}
.mm-trilha-panel.open{display:flex}.mm-trilha-head{padding:18px;border-bottom:1px solid #e4ebf0;display:flex;justify-content:space-between;gap:10px}.mm-trilha-head h3{margin:0;color:#08243b;font:700 22px 'Space Grotesk'}.mm-trilha-close{border:0;background:none;color:#718494;font-size:22px;cursor:pointer}.mm-trilha-list{overflow:auto;padding:8px 18px}.mm-trilha-item{display:grid;grid-template-columns:1fr auto;gap:10px;padding:12px 0;border-bottom:1px solid #edf1f4}.mm-trilha-item b{font:600 13px/1.25 'Space Grotesk';color:#173047}.mm-trilha-item button{border:0;background:none;color:#dd0f0f;font:800 9px Inter;cursor:pointer}.mm-trilha-empty{padding:25px 0;color:#718494;font-size:11px;line-height:1.6}.mm-trilha-actions{padding:14px 18px;border-top:1px solid #e4ebf0;display:grid;grid-template-columns:1fr 1fr;gap:8px}.mm-trilha-actions button,.mm-trilha-actions a{min-height:42px;display:grid;place-items:center;border:0;background:#08243b;color:#fff;font:800 9px Inter;letter-spacing:.05em;text-transform:uppercase;cursor:pointer}.mm-trilha-actions .wa{background:#25d366}.mm-trilha-add{display:inline-flex;align-items:center;justify-content:center;border:1px solid #cfdde6;background:#fff;color:#0568bf;padding:8px 10px;font:800 8px Inter;letter-spacing:.07em;cursor:pointer;text-transform:uppercase}.mm-trilha-add.added{background:#eef7fb;border-color:#8dc1df;color:#173047}.mm-trilha-add:disabled{opacity:.7;cursor:default}
@media(max-width:600px){.mm-trilha-fab{left:12px;bottom:12px}.mm-trilha-panel{left:12px;bottom:56px;width:calc(100vw - 24px);max-height:66vh}}`;
document.head.appendChild(style);
const fab=document.createElement('button');fab.type='button';fab.className='mm-trilha-fab';fab.innerHTML='<span>MINHA TRILHA</span><strong>0</strong>';document.body.appendChild(fab);
const panel=document.createElement('aside');panel.className='mm-trilha-panel';panel.innerHTML='<div class="mm-trilha-head"><h3>Minha trilha</h3><button class="mm-trilha-close" type="button" aria-label="Fechar">×</button></div><div class="mm-trilha-list"></div><div class="mm-trilha-actions"><button type="button" class="clear">LIMPAR</button><a class="wa" href="#" target="_blank" rel="noopener">ENVIAR NO WHATSAPP</a></div>';document.body.appendChild(panel);
const listEl=panel.querySelector('.mm-trilha-list'), countEl=fab.querySelector('strong');
function render(){items=read();countEl.textContent=items.length;document.querySelectorAll('[data-trail-add]').forEach(b=>{const has=items.some(x=>x.slug===b.dataset.trailAdd);b.classList.toggle('added',has);b.textContent=has?'ADICIONADO ✓':'ADICIONAR À TRILHA';b.disabled=has});
listEl.innerHTML=items.length?items.map((x,i)=>'<div class="mm-trilha-item"><b>'+x.name.replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))+'</b><button type="button" data-remove="'+i+'">REMOVER</button></div>').join(''):'<div class="mm-trilha-empty">Selecione até 5 cursos para comparar sua intenção e depois peça orientação à equipe.</div>';
panel.querySelector('.wa').href='https://wa.me/5522996172167?text='+encodeURIComponent('Olá! Montei esta trilha no site da MultiMarine e quero orientação:\n'+items.map(x=>'• '+x.name).join('\n')+'\n\nPode me ajudar a confirmar requisitos, turma, modalidade e próximos passos?');}
function add(name,slug){if(items.some(x=>x.slug===slug))return;if(items.length>=MAX){panel.classList.add('open');return}write([...items,{name,slug}]);panel.classList.add('open')}
document.addEventListener('click',e=>{const b=e.target.closest('[data-trail-add]');if(b){e.preventDefault();e.stopPropagation();add(b.dataset.trailName||'Curso',b.dataset.trailAdd)}const rm=e.target.closest('[data-remove]');if(rm){const next=items.filter((_,i)=>i!==Number(rm.dataset.remove));write(next)}});
fab.addEventListener('click',()=>panel.classList.toggle('open'));panel.querySelector('.mm-trilha-close').addEventListener('click',()=>panel.classList.remove('open'));panel.querySelector('.clear').addEventListener('click',()=>write([]));render();})();